description: Runs the process of creating GitHub Release with bump type and git ref
inputs:
  action_ref:
    default: ${{ github.action_ref }}
  owner:
    description: The owner for the command.
    required: true
  ref:
    description: The ref for the command.
    required: true
  repo:
    description: The repo for the command.
    required: true
  token:
    description: The token for the command.
    required: true
  type:
    description: The type for the command.
    required: true
name: Release
runs:
  steps:
  - name: Setup Swift
    uses: swift-actions/setup-swift@v2
    with:
      swift-version: 5.10.0
  - name: Create Mintfile
    run: echo Wei18/GitHubSwiftActions@${{ inputs.action_ref }} > Mintfile
    shell: bash
  - name: Setup Mint
    uses: irgaly/setup-mint@v1
    with:
      cache-prefix: GitHubSwiftActions
      mint-executable-directory: ~/.mint/bin
  - env:
      ACTION_REF: ${{ inputs.action_ref }}
      OWNER: ${{ inputs.owner }}
      REF: ${{ inputs.ref }}
      REPO: ${{ inputs.repo }}
      TOKEN: ${{ inputs.token }}
      TYPE: ${{ inputs.type }}
    name: Run Release
    run: ~/.mint/bin/mint run Wei18/GitHubSwiftActions Release
    shell: bash
  - name: Create Mintfile
    run: rm Mintfile
    shell: bash
  using: composite
