description: Runs the process of creating GitHub Release with bump type and git ref
inputs:
  owner:
    description: The owner for the command.
    required: true
  ref:
    description: The ref for the command.
    required: true
  repo:
    description: The repo for the command.
    required: true
  token:
    description: The token for the command.
    required: true
  type:
    description: The type for the command.
    required: true
name: Release
runs:
  steps:
  - name: Setup Swift, Mint, Cache, etc.
    uses: ${{ github.action_path }}/../SetUp
  - env:
      OWNER: ${{ inputs.owner }}
      REF: ${{ inputs.ref }}
      REPO: ${{ inputs.repo }}
      TOKEN: ${{ inputs.token }}
      TYPE: ${{ inputs.type }}
    name: Run Release
    run: ~/.mint/bin/mint run Wei18/GitHubSwiftActions Release
    shell: bash
  using: composite
