description: Runs the process of creating GitHub Release with bump type and git ref
inputs:
  bumpType:
    description: The bumpType for the command.
    required: true
  gitRef:
    description: The gitRef for the command.
    required: true
  owner:
    description: The owner for the command.
    required: true
  repo:
    description: The repo for the command.
    required: true
  token:
    description: The token for the command.
    required: true
name: Release
runs:
  steps:
  - name: Setup Swift, Mint, Cache, etc.
    uses: Wei18/GitHubSwiftActions/Actions/SetUp@main
  - env:
      BUMPTYPE: ${{ inputs.bumpType }}
      GITREF: ${{ inputs.gitRef }}
      OWNER: ${{ inputs.owner }}
      REPO: ${{ inputs.repo }}
      TOKEN: ${{ inputs.token }}
    name: Run Release
    run: ~/.mint/bin/mint run Wei18/GitHubSwiftActions@main Release
    shell: bash
  using: composite
