description: Runs the process of adding or updating a comment in a GitHub issue or pull request.
inputs:
  action_ref:
    default: ${{ github.action_ref }}
  anchor:
    description: The anchor for the command.
    required: true
  body:
    description: The body for the command.
    required: true
  number:
    description: The number for the command.
    required: true
  owner:
    description: The owner for the command.
    required: true
  repo:
    description: The repo for the command.
    required: true
  token:
    description: The token for the command.
    required: true
name: Comment
runs:
  steps:
  - name: Setup Swift
    uses: swift-actions/setup-swift@v2
    with:
      swift-version: 5.10.0
  - name: Create Mintfile
    run: echo Wei18/GitHubSwiftActions@${{ inputs.action_ref }} > ${{ github.action_path }}/Mintfile
    shell: bash
  - name: Setup Mint
    uses: irgaly/setup-mint@v1
    with:
      cache-prefix: GitHubSwiftActions
      mint-directory: ${{ github.action_path }}
      mint-executable-directory: ~/.mint/bin
  - env:
      ACTION_REF: ${{ inputs.action_ref }}
      ANCHOR: ${{ inputs.anchor }}
      BODY: ${{ inputs.body }}
      NUMBER: ${{ inputs.number }}
      OWNER: ${{ inputs.owner }}
      REPO: ${{ inputs.repo }}
      TOKEN: ${{ inputs.token }}
    name: Run Comment
    run: ~/.mint/bin/mint run Wei18/GitHubSwiftActions Comment
    shell: bash
  using: composite
