name: SetUp
runs:
  steps:
  - name: Setup Swift
    uses: swift-actions/setup-swift@v2
    with:
      swift-version: 5.10.0
  - name: Create Mintfile
    run: echo Wei18/GitHubSwiftActions@main > ${{ github.action_path }}/Mintfile
    shell: bash
  - name: Setup Mint
    uses: irgaly/setup-mint@v1
    with:
      cache-prefix: GitHubSwiftActions
      mint-directory: ${{ github.action_path }}
      mint-executable-directory: ~/.mint/bin
  using: composite
