name: Test

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:

  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          # - macos-latest
        swift: [5]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - run: |
          swift build
          swift test